### ISSUE TITLE
Grafana GPG key rotation

### ISSUE THREAD

**Issue by julestalloen** [relaxdiego/charm-k8s-grafana#17]
Grafana [recently rotated their GPG key](https://grafana.com/blog/2023/01/12/grafana-labs-update-regarding-circleci-security-updates/). As a result, the charm fails to install Grafana:
```
unit-grafana-1: 14:30:06 INFO juju.worker.uniter found queued "install" hook
unit-grafana-1: 14:30:29 WARNING unit.grafana/1.install ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.
unit-grafana-1: 14:30:31 INFO unit.grafana/1.juju-log Reactive main running for hook install
unit-grafana-1: 14:30:31 ERROR unit.grafana/1.juju-log Unable to find implementation for relation: requires of register-application
unit-grafana-1: 14:30:31 INFO unit.grafana/1.juju-log Initializing Snap Layer
unit-grafana-1: 14:30:31 INFO unit.grafana/1.juju-log Invoking reactive handler: reactive/grafana.py:205:install_packages
unit-grafana-1: 14:30:37 WARNING unit.grafana/1.install W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
unit-grafana-1: 14:30:37 WARNING unit.grafana/1.install E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
unit-grafana-1: 14:30:37 INFO unit.grafana/1.juju-log Failed executing 'add-apt-repository --yes deb https://packages.grafana.com/oss/deb stable main'. Will retry in 10 seconds
unit-grafana-1: 14:30:50 WARNING unit.grafana/1.install W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
unit-grafana-1: 14:30:50 WARNING unit.grafana/1.install E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
unit-grafana-1: 14:30:50 INFO unit.grafana/1.juju-log Couldn't acquire DPKG lock. Will retry in 10 seconds
unit-grafana-1: 14:31:02 WARNING unit.grafana/1.install W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
unit-grafana-1: 14:31:02 WARNING unit.grafana/1.install E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
unit-grafana-1: 14:31:02 INFO unit.grafana/1.juju-log Couldn't acquire DPKG lock. Will retry in 10 seconds
unit-grafana-1: 14:31:14 WARNING unit.grafana/1.install W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
unit-grafana-1: 14:31:14 WARNING unit.grafana/1.install E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
unit-grafana-1: 14:31:14 INFO unit.grafana/1.juju-log Couldn't acquire DPKG lock. Will retry in 10 seconds
unit-grafana-1: 14:31:25 WARNING unit.grafana/1.install W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
unit-grafana-1: 14:31:25 WARNING unit.grafana/1.install E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
unit-grafana-1: 14:31:25 INFO unit.grafana/1.juju-log Couldn't acquire DPKG lock. Will retry in 10 seconds
unit-grafana-1: 14:31:37 WARNING unit.grafana/1.install W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
unit-grafana-1: 14:31:37 WARNING unit.grafana/1.install E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
unit-grafana-1: 14:31:37 INFO unit.grafana/1.juju-log Couldn't acquire DPKG lock. Will retry in 10 seconds
unit-grafana-1: 14:31:49 WARNING unit.grafana/1.install W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
unit-grafana-1: 14:31:49 WARNING unit.grafana/1.install E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
unit-grafana-1: 14:31:49 INFO unit.grafana/1.juju-log Couldn't acquire DPKG lock. Will retry in 10 seconds
unit-grafana-1: 14:32:01 WARNING unit.grafana/1.install W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
unit-grafana-1: 14:32:01 WARNING unit.grafana/1.install E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
unit-grafana-1: 14:32:01 INFO unit.grafana/1.juju-log Couldn't acquire DPKG lock. Will retry in 10 seconds
unit-grafana-1: 14:32:12 WARNING unit.grafana/1.install W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
unit-grafana-1: 14:32:12 WARNING unit.grafana/1.install E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
unit-grafana-1: 14:32:12 INFO unit.grafana/1.juju-log Couldn't acquire DPKG lock. Will retry in 10 seconds
unit-grafana-1: 14:32:24 WARNING unit.grafana/1.install W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
unit-grafana-1: 14:32:24 WARNING unit.grafana/1.install E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
unit-grafana-1: 14:32:24 INFO unit.grafana/1.juju-log Couldn't acquire DPKG lock. Will retry in 10 seconds
unit-grafana-1: 14:32:36 WARNING unit.grafana/1.install W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
unit-grafana-1: 14:32:36 WARNING unit.grafana/1.install E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
unit-grafana-1: 14:32:36 INFO unit.grafana/1.juju-log Couldn't acquire DPKG lock. Will retry in 10 seconds
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install W: GPG error: https://packages.grafana.com/oss/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9E439B102CF3C0C6
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install E: The repository 'https://packages.grafana.com/oss/deb stable InRelease' is not signed.
unit-grafana-1: 14:32:48 ERROR unit.grafana/1.juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-grafana-1/.venv/lib/python3.8/site-packages/charms/reactive/__init__.py", line 74, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-grafana-1/.venv/lib/python3.8/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-grafana-1/.venv/lib/python3.8/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-grafana-1/.venv/lib/python3.8/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-grafana-1/charm/reactive/grafana.py", line 258, in install_packages
    fetch.configure_sources(update=True)
  File "/var/lib/juju/agents/unit-grafana-1/.venv/lib/python3.8/site-packages/charmhelpers/fetch/__init__.py", line 149, in configure_sources
    _fetch_update(fatal=True)
  File "/var/lib/juju/agents/unit-grafana-1/.venv/lib/python3.8/site-packages/charmhelpers/fetch/ubuntu.py", line 400, in apt_update
    _run_apt_command(cmd, fatal)
  File "/var/lib/juju/agents/unit-grafana-1/.venv/lib/python3.8/site-packages/charmhelpers/fetch/ubuntu.py", line 945, in _run_apt_command
    _run_with_retries(
  File "/var/lib/juju/agents/unit-grafana-1/.venv/lib/python3.8/site-packages/charmhelpers/fetch/ubuntu.py", line 922, in _run_with_retries
    result = subprocess.check_call(cmd, env=env, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-get', 'update']' returned non-zero exit status 100.

unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install Traceback (most recent call last):
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install   File "/var/lib/juju/agents/unit-grafana-1/charm/hooks/install", line 22, in <module>
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install     main()
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install   File "/var/lib/juju/agents/unit-grafana-1/.venv/lib/python3.8/site-packages/charms/reactive/__init__.py", line 74, in main
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install     bus.dispatch(restricted=restricted_mode)
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install   File "/var/lib/juju/agents/unit-grafana-1/.venv/lib/python3.8/site-packages/charms/reactive/bus.py", line 390, in dispatch
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install     _invoke(other_handlers)
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install   File "/var/lib/juju/agents/unit-grafana-1/.venv/lib/python3.8/site-packages/charms/reactive/bus.py", line 359, in _invoke
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install     handler.invoke()
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install   File "/var/lib/juju/agents/unit-grafana-1/.venv/lib/python3.8/site-packages/charms/reactive/bus.py", line 181, in invoke
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install     self._action(*args)
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install   File "/var/lib/juju/agents/unit-grafana-1/charm/reactive/grafana.py", line 258, in install_packages
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install     fetch.configure_sources(update=True)
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install   File "/var/lib/juju/agents/unit-grafana-1/.venv/lib/python3.8/site-packages/charmhelpers/fetch/__init__.py", line 149, in configure_sources
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install     _fetch_update(fatal=True)
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install   File "/var/lib/juju/agents/unit-grafana-1/.venv/lib/python3.8/site-packages/charmhelpers/fetch/ubuntu.py", line 400, in apt_update
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install     _run_apt_command(cmd, fatal)
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install   File "/var/lib/juju/agents/unit-grafana-1/.venv/lib/python3.8/site-packages/charmhelpers/fetch/ubuntu.py", line 945, in _run_apt_command
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install     _run_with_retries(
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install   File "/var/lib/juju/agents/unit-grafana-1/.venv/lib/python3.8/site-packages/charmhelpers/fetch/ubuntu.py", line 922, in _run_with_retries
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install     result = subprocess.check_call(cmd, env=env, **kwargs)
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install     raise CalledProcessError(retcode, cmd)
unit-grafana-1: 14:32:48 WARNING unit.grafana/1.install subprocess.CalledProcessError: Command '['apt-get', 'update']' returned non-zero exit status 100.
unit-grafana-1: 14:32:48 ERROR juju.worker.uniter.operation hook "install" (via explicit, bespoke hook script) failed: exit status 1
unit-grafana-1: 14:32:48 INFO juju.worker.uniter awaiting error resolution for "install" hook
```

**Comment by julestalloen** [comment]
https://bugs.launchpad.net/charm-grafana/+bug/2002776
